version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  goimports:
    local-prefixes: github.com/CoxxA/nomadbank

issues:
  exclude-use-default: false
