/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 进程正常 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 数据库可用 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询是否已经初始化 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 初始化状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            initialized: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建唯一所有者 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupInput"];
                };
            };
            responses: {
                /** @description 初始化完成并设置会话 Cookie */
                201: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
                413: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                413: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        /** 退出当前会话 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已退出 */
                204: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有者资料 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当前所有者 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        /** 更新显示名称和时区 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 可为空字符串，用于清除显示名称 */
                        display_name: string;
                        /** @example Asia/Shanghai */
                        timezone: string;
                    };
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Owner"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改密码并撤销其他会话 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        current_password: string;
                        /**
                         * Format: password
                         * @description 至少 10 个 Unicode 字符，UTF-8 编码后最多 72 字节
                         */
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description 密码已更新 */
                204: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取全部银行账户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账户列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        /** 创建银行账户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountInput"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                409: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** 获取账户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账户 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        /** 更新账户 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountInput"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        post?: never;
        /** 删除未被任务引用的账户 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取全部策略 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 策略列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"][];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        /** 创建策略 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StrategyInput"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                409: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** 获取策略 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 策略 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        /** 更新策略 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StrategyInput"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        post?: never;
        /** 删除策略 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除，历史批次保留策略名称 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取任务批次 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 批次列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskBatch"][];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        /** 生成任务批次 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        strategy_id: number;
                        /** @default  */
                        group_name?: string;
                        /** @default 4 */
                        cycles?: number;
                    };
                };
            };
            responses: {
                /** @description 已生成 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            batch: components["schemas"]["TaskBatch"];
                            tasks: number;
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                413: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除任务批次及其任务 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页获取任务 */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "completed";
                    batch_id?: number;
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务分页 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskPage"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 幂等地完成任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已完成；重复调用返回原完成时间 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取仪表盘摘要 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 摘要、即将执行与最近完成任务 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        Error: {
            code: string;
            message: string;
        };
        SetupInput: {
            username: string;
            /**
             * Format: password
             * @description 至少 10 个 Unicode 字符，UTF-8 编码后最多 72 字节
             */
            password: string;
            display_name?: string;
            /**
             * @description 省略或传空字符串时使用 Asia/Shanghai
             * @default Asia/Shanghai
             * @example Asia/Shanghai
             */
            timezone?: string;
        };
        Owner: {
            username: string;
            display_name: string;
            timezone: string;
        };
        AccountInput: {
            name: string;
            group_name: string;
            active: boolean;
        };
        Account: components["schemas"]["AccountInput"] & {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        StrategyInput: {
            name: string;
            interval_min_days: number;
            interval_max_days: number;
            time_start_minutes: number;
            time_end_minutes: number;
            skip_weekends: boolean;
            /** Format: int64 */
            amount_min_cents: number;
            /** Format: int64 */
            amount_max_cents: number;
            daily_limit: number;
        };
        Strategy: components["schemas"]["StrategyInput"] & {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TaskBatch: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            strategy_id: number | null;
            strategy_name: string;
            group_name: string;
            cycle_count: number;
            task_count: number;
            /** Format: date-time */
            created_at: string;
        };
        Task: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            batch_id: number;
            cycle_no: number;
            /** Format: date-time */
            scheduled_at: string;
            /** Format: int64 */
            from_account_id: number;
            from_account_name: string;
            /** Format: int64 */
            to_account_id: number;
            to_account_name: string;
            /** Format: int64 */
            amount_cents: number;
            /** @enum {string} */
            status: "pending" | "completed";
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        TaskPage: {
            items: components["schemas"]["Task"][];
            /** Format: int64 */
            total: number;
            page: number;
            page_size: number;
        };
        Dashboard: {
            /** Format: int64 */
            total_accounts: number;
            /** Format: int64 */
            active_accounts: number;
            /** Format: int64 */
            pending_tasks: number;
            /** Format: int64 */
            completed_tasks: number;
            /** Format: int64 */
            strategies: number;
            upcoming: components["schemas"]["Task"][];
            recent: components["schemas"]["Task"][];
        };
    };
    responses: {
        /** @description 请求失败 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ID: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
